### ISSUE TITLE
Example 26.MM2Interface.ino doesn't compile

### ISSUE THREAD

**Issue by Jueff** [Hardi-St/MobaLedLib#15]
Compilation of 26.MM2Interface.ino fails, even if the patched library https://github.com/oliwel/MaerklinMotorola/ is installed.

Seams that @oliwel 's patched library in github isn't the latest version.

e.g. definition of MM2DecoderState_Red and MM2DecoderState_Green is missing.

**Comment by oliwel** [comment]
I had those changes only in my develop branch, merged them to master now so you should be able to compile it using "my" master branch.

**Comment by Jueff** [comment]
Thank you @oliwel, now it compiles as expected. Maybe you can create a Pull-Request that your changes are merged to the official library https://github.com/Laserlicht/MaerklinMotorola ?

**Comment by oliwel** [comment]
@Jueff I have already contacted them when I wrote the code but never got a response :(
I made a PR yesterday, so lets see https://github.com/Laserlicht/MaerklinMotorola/pull/4

**Comment by Laserlicht** [comment]
@oliwel Merged.

Sorry for the late response. Can you test it?
