### ISSUE TITLE
Frage zum Servo Code

### ISSUE THREAD

**Issue by psander247** [Hardi-St/MobaLedLib#4]
Hallo zusammen, 

ich hätte eine Frage zum Programmcode der Servo Platine. 
Lässt sich die Erkennung der PWM evtl auch auf einem Arduino (Nano) betreiben?
Ich würde gerne die 3 Farbkanäle einlesen und verarbeiten. 
Am ende soll mit Timer1 eine höher aufgelöste PWM erzeugt werden. 

Ziel von meinem Projekt ist  es mit einem Ws2811 eine weiße High-Power Led mit entsprechendem CC-Treiber anzusteuern. 
Bei 8 Bit PWM hat man im unteren Helligkeitsbereich der  Led leider deutliche Stufen, daher wollte ich dies durch Verrechnung von den 3 PWMs verbessern. 

Danke schonmal im Voraus :)

**Comment by Jueff** [comment]
yes, that should be possible, maybe the code in https://github.com/Hardi-St/MobaLedLib/blob/master/examples/80.Modules/03.ATTiny85_Sound/03.ATTiny85_Sound.ino helps. Looks like "// Debug CPU" is an ATMega328. You should use WS2811 THT chips, the LED PWM speed is 1/3 of the WS2811 smd chip and therefore easier to process.
